---
title: "Untitled"
author: "Jaehwan Lim"
date: "January 12, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)

leader_profile <- read_dta("leaders_datapaper_replication_final_9_10_15.dta")

leader_article <- read_dta("S0020818314000046sup002.dta")

theme_set(theme_light())

```

```{r}
leader_profile %>% 
  count(dadwork, sort = T)

leader_processed <- leader_profile %>% 
  select(idacr, ccode, year, leadername, inyear, outyear, age, gender, married, onlychild, firstborn, leveledu, milservice, combat, rebel, miledu, medicine, economics, physhealth) %>% 
  mutate(leveledu = recode(leveledu, `0` = 0, `1` = 0,  `2` = 1, `3` = 1)) 

leader_processed %>% 
  count(ccode, sort = T)

```

```{r}
library(broom)

leader_article_processed <- leader_article %>% 
  select(leaderid, leadername, ccode, year, age, milservice, milnoncombat, combat, rebel, rebelwin, rebelloss, leveledu, teacher, journalism, law, engineering, labor, police, careerpolitician, militarycareer, businesscareer, cwinit) %>% 
  mutate(leveledu = recode(leveledu, `0` = 0, `1` = 0,  `2` = 1, `3` = 1)) %>%
  mutate(age = ifelse(age > 50, 1, 0)) %>% 
  filter(!is.na(combat))

mod <- glm(cwinit ~ milnoncombat + 
             combat + 
             rebel +
             age +
             leveledu + 
             law + 
             engineering + 
             labor +
             businesscareer +
             militarycareer + 
             careerpolitician, 
    data = leader_article_processed, 
    family = binomial) 

estimate_leaders <- tidy(mod)
confint_leaders <- confint_tidy(mod)

estimate_confint <- bind_cols(estimate_leaders, confint_leaders)

estimate_confint_subset <- estimate_confint[2:12, ] 

estimate_confint_subset %>% 
  mutate(term = recode(term, milnoncombat = "兵役（戦闘経験なし）", 
                       combat = "兵役（戦闘経験あり）", 
                       engineering = "職業（エンジニア－）", 
                       rebel = "反乱（参加あり）", 
                       age = "年齢（50歳以上）", 
                       leveledu = "教育（大学以上）",
                       labor = "職業（労働）", 
                       careerpolitician = "職業（政治家）", 
                       law = "職業（法曹）", 
                       businesscareer = "職業（実業家）", 
                       militarycareer = "職業（軍人）")) %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(term, estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high, width = 0.2)) +
  coord_flip() +
  labs(title = "図1. リーダーの経歴と対外武力行使", 
       x = "", 
       y = "推定値（ロジスティックモデル）") +
  theme_bw(base_family = "HiraKakuProN-W6")


```

